# Generated by Django 3.0.5 on 2020-04-22 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200422_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=200, null=True),
        ),
    ]
