# Generated by Django 3.0.5 on 2020-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200422_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Enrolled', 'Enrolled')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(choices=[('Dobbs Ferry', 'Dobbs Ferry'), ('Manhattan', 'Manhattan'), ('Bronx', 'Bronx')], max_length=200, null=True),
        ),
    ]
